STRINGS.NAMES.CCS_MAGIC_WAND1 = "知世的手杖"    
STRINGS.RECIPE_DESC.CCS_MAGIC_WAND1 = "帮知世做个手杖啊"  --配方描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_MAGIC_WAND1 = "这个是知世用的手杖"  --检查描述

STRINGS.NAMES.CCS_MAGIC_WAND2 = "樱花法杖"    
STRINGS.RECIPE_DESC.CCS_MAGIC_WAND2 = "给小樱的工具" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_MAGIC_WAND2 = "属于小樱的工具"

STRINGS.NAMES.CCS_MAGIC_WAND3 = "魔杖"    
STRINGS.RECIPE_DESC.CCS_MAGIC_WAND3 = "魔杖" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_MAGIC_WAND3 = "魔杖"

STRINGS.NAMES.CCS_CARD_BOX = "卡牌盒"    
STRINGS.RECIPE_DESC.CCS_CARD_BOX = "小樱的卡牌盒" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_CARD_BOX = "小樱的卡牌盒"

STRINGS.NAMES.CCS_HAT1 = "樱花魔法帽"    
STRINGS.RECIPE_DESC.CCS_HAT1 = "知世给小樱做的帽子" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_HAT1 = "属于库洛魔法使小樱的帽子"

STRINGS.NAMES.WALL_CCS_WALL1 = "花墙"    
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_CCS_WALL1 = "好漂亮的墙"

STRINGS.NAMES.WALL_CCS_WALL1_ITEM = "花墙"    
STRINGS.RECIPE_DESC.WALL_CCS_WALL1_ITEM = "美丽的墙像我一样" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_CCS_WALL1_ITEM = "好漂亮的墙"

STRINGS.NAMES.CCS_JT = "魔法祭坛"    
STRINGS.RECIPE_DESC.CCS_JT = "魔法使用魔法做的祭坛" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_JT = "有强力的魔法波动"

STRINGS.NAMES.CCS_LIGHT = "小樱的樱花祈愿站(未修复)"    
STRINGS.RECIPE_DESC.CCS_LIGHT = "未修复的樱花祈愿站" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_LIGHT = "未修复的樱花祈愿站"

STRINGS.NAMES.CCS_LIGHT2 = "小樱的樱花祈愿站"    
STRINGS.RECIPE_DESC.CCS_LIGHT2 = "祈愿掉一些有用的樱花吧" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_LIGHT2 = "祈愿掉一些有用的樱花吧"

STRINGS.NAMES.CCS_SKIRT1 = "小樱的衣服"    
STRINGS.RECIPE_DESC.CCS_SKIRT1 = "结合远古与魔法的产品" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_SKIRT1 = "有强力的魔法波动"

STRINGS.NAMES.CCS_CHEST = "小樱的暗黑盒子"    
STRINGS.RECIPE_DESC.CCS_CHEST = "好像有一点斯比的气味" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_CHEST = "可爱的小熊箱子"

STRINGS.NAMES.CCS_CHEST2 = "雪白小熊箱子"     
STRINGS.RECIPE_DESC.CCS_CHEST2 = "可以返鲜一些食物" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_CHEST2 = "它好恐怖，可以吃东西"

STRINGS.NAMES.CCS_FLOWER = "花"    
STRINGS.RECIPE_DESC.CCS_FLOWER = "花" 

STRINGS.NAMES.CCS_CHEST3 = "黑色小熊箱子"    
STRINGS.RECIPE_DESC.CCS_CHEST3 = "可以快速腐烂一些东西" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_CHEST3 = "可爱的黑色小熊箱子"

STRINGS.NAMES.CCS_OVEN = "小樱的神奇烤箱"    
STRINGS.RECIPE_DESC.CCS_OVEN = "可以烤热制冷东西" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_OVEN = "雪兔哥送的烤箱好神奇"

STRINGS.NAMES.CCS_TENT = "小樱的魔法帐篷"    
STRINGS.RECIPE_DESC.CCS_TENT = "他可以恢复我的魔法" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_TENT = "可以恢复小樱的魔法的帐篷"

STRINGS.NAMES.CCS_AMULET = "小樱的护符"    
STRINGS.RECIPE_DESC.CCS_AMULET = "小樱的护身符" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_AMULET = "小樱的护身符"

STRINGS.NAMES.CCS_ICE_BOX = "小可的甜品箱子"    
STRINGS.RECIPE_DESC.CCS_ICE_BOX = "小可的甜品箱子" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_ICE_BOX = "小可的甜品箱子"

STRINGS.NAMES.CCS_TRASH = "樱花水晶球"    
STRINGS.RECIPE_DESC.CCS_TRASH = "可以删掉一些不用的东西提高祈愿站掉落" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_TRASH = "祈愿吧！"

STRINGS.NAMES.CCS_BROOM = "清除掸子"    
STRINGS.RECIPE_DESC.CCS_BROOM = "清楚绑定过主人的卡牌的主人" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_BROOM = "清楚绑定过主人的卡牌的主人"

STRINGS.NAMES.CCS_LIGHT3 = "樱花灯"    
STRINGS.RECIPE_DESC.CCS_LIGHT3 = "吸收同样物品的灯" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_LIGHT3 = "这个灯为什么在吸收东西"

STRINGS.NAMES.CCS_SAKURA_TREE3 = "樱花树"    
STRINGS.RECIPE_DESC.CCS_SAKURA_TREE3 = "樱花树！" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_SAKURA_TREE3 = "装饰好看的树"

STRINGS.NAMES.CCS_CRYSTAL_TREE = "水晶树"    
STRINGS.RECIPE_DESC.CCS_CRYSTAL_TREE = "亮晶晶的树" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_CRYSTAL_TREE = "装饰好看的树"

STRINGS.NAMES.CCS_STREET_LAMP = "樱花路灯"    
STRINGS.RECIPE_DESC.CCS_STREET_LAMP = "会发光的路灯" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_STREET_LAMP = "好漂亮的灯"

STRINGS.NAMES.CCS_PIANO = "魔法钢琴"    
STRINGS.RECIPE_DESC.CCS_PIANO = "靠近钢琴会解锁一些科技" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_PIANO = "魔力充盈的钢琴"

STRINGS.NAMES.CCS_SAKURA_TREE = "未完成的樱花巨树"    
STRINGS.RECIPE_DESC.CCS_SAKURA_TREE = "超大的樱花树可以保护我们" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_SAKURA_TREE = "好大好大的樱花树"

STRINGS.NAMES.CCS_SAKURA_TREE2 = "樱花巨树"    
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_SAKURA_TREE2 = "好大好大的樱花树"

STRINGS.NAMES.CCS_FOUNTAIN = "魔法喷泉"    
STRINGS.RECIPE_DESC.CCS_FOUNTAIN = "会保护植物和产生魔法水" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_FOUNTAIN = "好清甜的泉水"

STRINGS.NAMES.CCS_MINIBOATLANTERN = "水灯"    
STRINGS.RECIPE_DESC.CCS_MINIBOATLANTERN = "闪耀着光" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_MINIBOATLANTERN = "放到水里吧"

STRINGS.NAMES.CCS_CRYSTALLIZATION1 = "橙色结晶"     
STRINGS.RECIPE_DESC.CCS_CRYSTALLIZATION1 = "用宝石制作结晶" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_CRYSTALLIZATION1 = "强大的魔法能量"

STRINGS.NAMES.CCS_CRYSTALLIZATION2 = "蓝色结晶"    
STRINGS.RECIPE_DESC.CCS_CRYSTALLIZATION2 = "用宝石制作结晶" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_CRYSTALLIZATION2 = "强大的魔法能量"

STRINGS.NAMES.CCS_CRYSTALLIZATION3 = "紫色结晶"    
STRINGS.RECIPE_DESC.CCS_CRYSTALLIZATION3 = "用宝石制作结晶" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_CRYSTALLIZATION3 = "强大的魔法能量"

STRINGS.NAMES.FENCE_CCSSTRAWBERRY = "草莓栅栏"    
STRINGS.RECIPE_DESC.FENCE_CCSSTRAWBERRY = "栅栏用甜蜜阻挡" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FENCE_CCSSTRAWBERRY = "草莓做的栅栏可以吃吗"

STRINGS.NAMES.FENCE_CCSSTRAWBERRY_ITEM = "草莓栅栏"    
STRINGS.RECIPE_DESC.FENCE_CCSSTRAWBERRY_ITEM = "栅栏用甜蜜阻挡" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FENCE_CCSSTRAWBERRY_ITEM = "草莓做的栅栏可以吃吗"

STRINGS.NAMES.CCS_BEE = "蜜蜂"    
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_BEE = "蜜蜂~"

STRINGS.NAMES.CCS_GUARD = "天使的守护"    
STRINGS.RECIPE_DESC.CCS_GUARD = "有妈妈的感觉" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_GUARD = "更好的守护"

STRINGS.NAMES.CCS_FROG_YF = "青蛙雨衣"    
STRINGS.RECIPE_DESC.CCS_FROG_YF = "青蛙雨衣" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_FROG_YF = "青蛙雨衣"

STRINGS.NAMES.CCS_BEEBOX = "樱花蜂箱"    
STRINGS.RECIPE_DESC.CCS_BEEBOX = "友善蜜蜂的家" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_BEEBOX = "可爱蜜蜂的家"

STRINGS.NAMES.CCS_BUTTERFLY = "樱花蝴蝶"    
STRINGS.RECIPE_DESC.CCS_BUTTERFLY = "用魔法生成蝴蝶" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_BUTTERFLY = "美丽的蝴蝶美丽的我。"

STRINGS.NAMES.CCS_BAG = "小樱的背包"    
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_BAG = "只有库洛魔法使才能使用的背包"

STRINGS.NAMES.CCS_PAPER = "魔法纸"    
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_PAPER = "有着魔法力量的纸张"

STRINGS.NAMES.CCS_JELLY = "樱花果冻"    
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_JELLY = "飘着樱花的果冻~"

STRINGS.NAMES.CCS_YZS = "玉子烧"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_YZS = "知世为我做的玉子烧"

STRINGS.NAMES.CCS_SODA = "气泡水"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_SODA = "雪兔哥做的气泡水有股樱花的香味"

STRINGS.NAMES.CCS_MATCHA_CAKE = "抹茶蛋糕"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_MATCHA_CAKE = "好绿色的蛋糕"

STRINGS.NAMES.CCS_STRAWBERRY_FOOD1 = "草莓双皮奶"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_STRAWBERRY_FOOD1 = "好好吃的双皮奶"

STRINGS.NAMES.CCS_STRAWBERRY_FOOD2 = "草莓大福"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_STRAWBERRY_FOOD2 = "充满着魔力的食物"

STRINGS.NAMES.CCS_STRAWBERRY_FOOD3 = "草莓果冻"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_STRAWBERRY_FOOD3 = "QQ弹弹的果冻"

STRINGS.NAMES.CCS_TEA1 = "魔法奶茶"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_TEA1 = "充满着力量的奶茶"

STRINGS.NAMES.CCS_SPECIFICFOOD = "特级秘制"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_SPECIFICFOOD = "这能是什么好东西？"

STRINGS.RECIPE_DESC.CCS_CARDS_7 = "用多的卡牌做一张工作牌" 

STRINGS.NAMES.CCS_FX4 = ""    
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_FX4 = "传送到浮牌的主人身边"

STRINGS.NAMES.CCS_SAKURA1 = "紫樱花"    
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_SAKURA1 = "紫樱花"

STRINGS.NAMES.CCS_SAKURA2 = "白樱花"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_SAKURA2 = "白樱花"

STRINGS.NAMES.CCS_SAKURA3 = "粉樱花"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_SAKURA3 = "粉樱花"

STRINGS.NAMES.CCS_BAG2 = "魔法卡牌袋"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_BAG2 = "很可爱的小袋子"
STRINGS.RECIPE_DESC.CCS_BAG2 = "可以放一些卡牌"

STRINGS.NAMES.CCS_STARSTAFF = "星之杖"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_STARSTAFF = "使用星星的力量"
STRINGS.RECIPE_DESC.CCS_STARSTAFF = "小樱新的力量——星星的力量"

STRINGS.NAMES.CCS_LIFESTAFF = "生命法杖"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_LIFESTAFF = "生命的力量"
STRINGS.RECIPE_DESC.CCS_LIFESTAFF = "从自然中得到力量"

STRINGS.NAMES.CCS_THRONE = "毛绒地毯"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_THRONE = "毛绒绒的地毯好舒服"
STRINGS.RECIPE_DESC.CCS_THRONE = "软软的地毯"

STRINGS.NAMES.CCS_THRONE_FLOWER = "花朵地毯"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_THRONE_FLOWER = "花朵地毯"
STRINGS.RECIPE_DESC.CCS_THRONE_FLOWER = "花朵地毯"

STRINGS.NAMES.CCS_CHAIR = "月亮椅子"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_CHAIR = "月亮椅子"
STRINGS.RECIPE_DESC.CCS_CHAIR = "月亮椅子"

STRINGS.NAMES.CCS_TREASURECHEST = "小可的储物柜"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_TREASURECHEST = "放很多东西的储物柜"
STRINGS.RECIPE_DESC.CCS_TREASURECHEST = "小可的储物柜"

STRINGS.NAMES.CCS_FLOWERPOT = "魔法花盆"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_FLOWERPOT = "美丽的花盆"
STRINGS.RECIPE_DESC.CCS_FLOWERPOT = "可爱的花盆"

STRINGS.NAMES.CCS_SHIPWRECKED = "兔兔摇摇椅"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_SHIPWRECKED = "爸爸的爸爸叫………"
STRINGS.RECIPE_DESC.CCS_SHIPWRECKED = "可爱的摇摇椅"

STRINGS.NAMES.CCS_BUNNY_FLUORESCEN = "月光花"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_BUNNY_FLUORESCEN = "月光下的花光让我想起了一个人"
STRINGS.RECIPE_DESC.CCS_BUNNY_FLUORESCEN = "月光下的花朵"

STRINGS.NAMES.CCS_BUNNY_FLUORESCEN2 = "月光花朵"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_BUNNY_FLUORESCEN2 = "月光花朵好美"
STRINGS.RECIPE_DESC.CCS_BUNNY_FLUORESCEN2 = "月光下的花朵"

STRINGS.NAMES.CCS_BUNNY_FLUORESCEN_FRUIT = "月亮果"  
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_BUNNY_FLUORESCEN_FRUIT = "月亮花的果实"

STRINGS.NAMES.BRC_SWING = '秋千'
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BRC_SWING = '秋千'

STRINGS.NAMES.BRC_SWING_DOUBLE = '双人秋千'
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BRC_SWING_DOUBLE = '双人秋千'

STRINGS.NAMES.BRC_HOTSPRING = '温泉'
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BRC_HOTSPRING = '温泉'
STRINGS.RECIPE_DESC.BRC_HOTSPRING = "温泉"

STRINGS.NAMES.CCS_COOKPOT = "魔法香水瓶"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_COOKPOT = "香水瓶里面充满了什么？"

STRINGS.NAMES.CCS_COOKPOT_ITEM = "魔法香水瓶"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_COOKPOT_ITEM = "香水瓶里面充满了什么？"
STRINGS.RECIPE_DESC.CCS_COOKPOT_ITEM = "香水瓶？魔法锅罢了！"

STRINGS.NAMES.CCS_COOKPOT2 = "魔法沙漏"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_COOKPOT2 = "沙漏在不停流失回流"
STRINGS.RECIPE_DESC.CCS_COOKPOT2 = "神奇沙漏"

STRINGS.NAMES.CCS_COOKPOT2 = "魔法沙漏"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_COOKPOT2 = "沙漏在不停流失回流"
STRINGS.RECIPE_DESC.CCS_COOKPOT2 = "神奇沙漏"

STRINGS.NAMES.TURF_CCS_GREEN = "绿色地皮"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CCS_GREEN = "绿色地皮"
STRINGS.RECIPE_DESC.TURF_CCS_GREEN = "绿色地皮"
STRINGS.NAMES.TURF_CCS_RED = "粉色地皮"   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CCS_RED = "粉色地皮"
STRINGS.RECIPE_DESC.TURF_CCS_RED = "粉色地皮"

--这是制作栏
STRINGS.NAMES.CCS_XK_ITEM = "小可"                   
STRINGS.RECIPE_DESC.CCS_XK_ITEM = "领养一只小可"

STRINGS.NAMES.CCS_SB_ITEM = "斯比"                   
STRINGS.RECIPE_DESC.CCS_SB_ITEM = "领养一只斯比"

--这是宠物
STRINGS.NAMES.CCS_XK = "小可"                   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_XK = "小樱的宠物" 

STRINGS.NAMES.CCS_SB = "斯比"                   
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CCS_SB = "小樱的宠物" 


STRINGS.NAMES.CCS_MAGIC_WAND1_PIANO = STRINGS.NAMES.CCS_MAGIC_WAND1
STRINGS.NAMES.CCS_CHEST_PIANO = STRINGS.NAMES.CCS_CHEST     
STRINGS.NAMES.CCS_ICE_BOX_PIANO = STRINGS.NAMES.CCS_ICE_BOX
STRINGS.NAMES.CCS_CHEST2_PIANO = STRINGS.NAMES.CCS_CHEST2 